-- Supabase local schema for this project
-- Target: local/dev bootstrap with the current totem + admin + automation flow
-- Notes:
-- 1) This file is intentionally permissive for LOCAL use.
-- 2) RLS policies below are not production-hardened.
-- 3) It includes legacy/customer/admin helpers still referenced by the codebase.

begin;
create extension if not exists pgcrypto;

-- =========================================================
-- HELPERS
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.only_digits(input text)
returns text
language sql
immutable
as $$
  select regexp_replace(coalesce(input, ''), '\D', '', 'g');
$$;

create sequence if not exists public.order_number_seq start 1000;

create or replace function public.generate_order_number()
returns text
language plpgsql
as $$
declare
  seq_value bigint;
begin
  seq_value := nextval('public.order_number_seq');
  return 'GM-' || to_char(current_date, 'YYYYMMDD') || '-' || lpad(seq_value::text, 6, '0');
end;
$$;

-- =========================================================
-- CORE TABLES
-- =========================================================

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'employee',
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete set null,
  document text unique,
  name text,
  full_name text,
  email text,
  phone text,
  role text not null default 'cliente',
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists customers_document_idx on public.customers(document);
create index if not exists customers_user_id_idx on public.customers(user_id);

create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete set null,
  cpf text not null unique,
  full_name text not null,
  role text not null default 'employee',
  active boolean not null default true,
  department text,
  job_title text,
  monthly_credit_cents integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists employees_cpf_idx on public.employees(cpf);
create index if not exists employees_user_id_idx on public.employees(user_id);

create table if not exists public.hr_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  old_id bigint unique,
  name text not null,
  description text,
  category text,
  category_id bigint references public.categories(id) on delete set null,
  package_info text,
  packageinfo text,
  image_path text,
  images text[] not null default '{}',
  image_url text,
  price numeric(12,2) not null default 0,
  employee_price numeric(12,2) not null default 0,
  customer_price numeric(12,2),
  retail_price numeric(12,2),
  wholesale_price numeric(12,2),
  price_public numeric(12,2),
  price_employee numeric(12,2),
  price_cpf_varejo numeric(12,2) not null default 0,
  price_cpf_atacado numeric(12,2) not null default 0,
  price_cnpj_varejo numeric(12,2) not null default 0,
  price_cnpj_atacado numeric(12,2) not null default 0,
  weight numeric(12,3) not null default 0,
  is_package boolean not null default false,
  in_stock boolean not null default true,
  featured boolean not null default false,
  is_launch boolean not null default false,
  active boolean not null default true,
  display_order integer not null default 999999,
  sort_order integer not null default 0,
  extra_info jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists products_old_id_idx on public.products(old_id);
create index if not exists products_name_idx on public.products(name);
create index if not exists products_category_idx on public.products(category);
create index if not exists products_display_order_idx on public.products(display_order, name);

create table if not exists public.weight (
  product_id uuid primary key references public.products(id) on delete cascade,
  weight numeric(12,3) not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique,
  customer_id uuid references public.customers(id) on delete set null,
  customer_document text,
  customer_name text,
  employee_id uuid references public.employees(id) on delete set null,
  employee_cpf text,
  employee_name text,
  payment_method text,
  total_items integer not null default 0,
  total_value numeric(12,2) not null default 0,
  total_cents integer not null default 0,
  wallet_used_cents integer not null default 0,
  spent_from_balance_cents integer not null default 0,
  pay_on_pickup_cents integer not null default 0,
  wallet_debited boolean not null default false,
  status text not null default 'aguardando_atendimento',
  saibweb_status text,
  saibweb_error text,
  saibweb_synced_at timestamptz,
  saibweb_external_id text,
  cancel_reason text,
  cancelled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_customer_document_idx on public.orders(customer_document);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_saibweb_status_idx on public.orders(saibweb_status);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_old_id text,
  product_name text not null,
  quantity numeric(12,3) not null default 1,
  unit_price_cents integer not null default 0,
  unit_price numeric(12,2) generated always as (unit_price_cents::numeric / 100) stored,
  total_price numeric(12,2) generated always as (((quantity * unit_price_cents::numeric) / 100)) stored,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists order_items_product_id_idx on public.order_items(product_id);
create index if not exists order_items_product_old_id_idx on public.order_items(product_old_id);

create table if not exists public.order_admin_actions (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  actor_cpf text,
  action text not null,
  reason text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists order_admin_actions_order_id_idx on public.order_admin_actions(order_id, created_at desc);

create table if not exists public.app_events (
  id uuid primary key default gen_random_uuid(),
  event_name text not null,
  severity text not null default 'info',
  message text not null,
  payload jsonb,
  source text not null default 'totem',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists app_events_created_at_idx on public.app_events(created_at desc);
create index if not exists app_events_event_name_idx on public.app_events(event_name, created_at desc);

create table if not exists public.notices (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  image_url text,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.favorites (
  id uuid primary key default gen_random_uuid(),
  customer_document text not null,
  product_id uuid references public.products(id) on delete cascade,
  product_old_id text,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists favorites_customer_product_uidx
on public.favorites(customer_document, coalesce(product_id::text, product_old_id));

create table if not exists public.featured_products (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  position integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  unique(product_id)
);

create table if not exists public.carousel_settings (
  id uuid primary key default gen_random_uuid(),
  auto_mode boolean not null default false,
  limit_count integer not null default 10,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- =========================================================
-- TRIGGERS
-- =========================================================

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_customers_updated_at on public.customers;
create trigger trg_customers_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists trg_employees_updated_at on public.employees;
create trigger trg_employees_updated_at
before update on public.employees
for each row execute function public.set_updated_at();

drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_weight_updated_at on public.weight;
create trigger trg_weight_updated_at
before update on public.weight
for each row execute function public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists trg_notices_updated_at on public.notices;
create trigger trg_notices_updated_at
before update on public.notices
for each row execute function public.set_updated_at();

drop trigger if exists trg_carousel_settings_updated_at on public.carousel_settings;
create trigger trg_carousel_settings_updated_at
before update on public.carousel_settings
for each row execute function public.set_updated_at();

create or replace function public.orders_before_insert_defaults()
returns trigger
language plpgsql
as $$
begin
  if new.order_number is null or btrim(new.order_number) = '' then
    new.order_number := public.generate_order_number();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_orders_before_insert_defaults on public.orders;
create trigger trg_orders_before_insert_defaults
before insert on public.orders
for each row execute function public.orders_before_insert_defaults();

create or replace function public.refresh_order_totals(p_order_id uuid)
returns void
language plpgsql
as $$
declare
  v_total_items integer := 0;
  v_total_cents integer := 0;
begin
  select
    coalesce(sum(coalesce(quantity, 0))::integer, 0),
    coalesce(sum(round(coalesce(quantity, 0) * coalesce(unit_price_cents, 0)))::integer, 0)
  into v_total_items, v_total_cents
  from public.order_items
  where order_id = p_order_id;

  update public.orders
     set total_items = v_total_items,
         total_cents = v_total_cents,
         total_value = v_total_cents::numeric / 100,
         updated_at = timezone('utc', now())
   where id = p_order_id;
end;
$$;

create or replace function public.order_items_after_change()
returns trigger
language plpgsql
as $$
declare
  v_order_id uuid;
begin
  v_order_id := coalesce(new.order_id, old.order_id);
  perform public.refresh_order_totals(v_order_id);
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_order_items_after_insert on public.order_items;
create trigger trg_order_items_after_insert
after insert on public.order_items
for each row execute function public.order_items_after_change();

drop trigger if exists trg_order_items_after_update on public.order_items;
create trigger trg_order_items_after_update
after update on public.order_items
for each row execute function public.order_items_after_change();

drop trigger if exists trg_order_items_after_delete on public.order_items;
create trigger trg_order_items_after_delete
after delete on public.order_items
for each row execute function public.order_items_after_change();

create or replace function public.create_order_v1(
  p_customer_id uuid default null,
  p_customer_document text default null,
  p_customer_name text default null,
  p_payment_method text default 'attendant',
  p_pay_on_pickup_cents integer default null,
  p_items jsonb default '[]'::jsonb
)
returns table (
  order_id uuid,
  order_number text,
  total_cents integer,
  pay_on_pickup_cents integer,
  status text
)
language plpgsql
as $$
declare
  v_order_id uuid;
  v_payment_method text := coalesce(nullif(btrim(p_payment_method), ''), 'attendant');
  v_channel text := case when lower(coalesce(p_payment_method, '')) like '%atacado%' then 'atacado' else 'varejo' end;
  v_items_count integer := 0;
  v_inserted_count integer := 0;
  v_total_cents integer := 0;
  v_pay_on_pickup integer := 0;
begin
  if p_customer_document is null or btrim(p_customer_document) = '' then
    raise exception 'customerDocument vazio.';
  end if;

  if p_customer_name is null or btrim(p_customer_name) = '' then
    raise exception 'customerName vazio.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Pedido sem itens.';
  end if;

  v_items_count := jsonb_array_length(p_items);
  if v_items_count = 0 then
    raise exception 'Pedido sem itens.';
  end if;

  insert into public.orders (
    customer_id,
    customer_document,
    customer_name,
    payment_method,
    wallet_debited,
    spent_from_balance_cents,
    status,
    saibweb_status,
    saibweb_error
  )
  values (
    p_customer_id,
    btrim(p_customer_document),
    btrim(p_customer_name),
    v_payment_method,
    false,
    0,
    'aguardando_atendimento',
    'PENDING',
    null
  )
  returning id into v_order_id;

  insert into public.order_items (
    order_id,
    product_id,
    product_old_id,
    product_name,
    quantity,
    unit_price_cents
  )
  select
    v_order_id,
    p.id,
    nullif(p.old_id::text, ''),
    coalesce(nullif(p.name, ''), 'Produto'),
    floor(i.quantity)::integer,
    case
      when v_channel = 'atacado' and coalesce(p.price_cnpj_atacado, 0) > 0 then round(p.price_cnpj_atacado * 100)::integer
      when v_channel = 'varejo' and coalesce(p.price_cpf_varejo, 0) > 0 then round(p.price_cpf_varejo * 100)::integer
      when coalesce(p.price, 0) > 0 then round(p.price * 100)::integer
      when coalesce(p.employee_price, 0) > 0 then round(p.employee_price * 100)::integer
      else 0
    end
  from jsonb_to_recordset(p_items) as i(product_id uuid, quantity numeric)
  join public.products p on p.id = i.product_id
  where i.quantity is not null
    and floor(i.quantity) > 0;

  get diagnostics v_inserted_count = row_count;

  if v_inserted_count <> v_items_count then
    raise exception 'Produto inválido ou desatualizado no carrinho.';
  end if;

  perform public.refresh_order_totals(v_order_id);

  select o.total_cents
    into v_total_cents
  from public.orders o
  where o.id = v_order_id;

  if v_total_cents <= 0 then
    raise exception 'Pedido sem valor válido.';
  end if;

  if lower(v_payment_method) like 'attendant%' and p_pay_on_pickup_cents is not null and p_pay_on_pickup_cents <> v_total_cents then
    raise exception 'Os preços do carrinho foram atualizados. Revise os itens antes de confirmar.';
  end if;

  v_pay_on_pickup := coalesce(
    p_pay_on_pickup_cents,
    case when lower(v_payment_method) like 'attendant%' then v_total_cents else 0 end
  );

  update public.orders
     set pay_on_pickup_cents = greatest(v_pay_on_pickup, 0),
         wallet_used_cents = 0,
         spent_from_balance_cents = 0,
         updated_at = timezone('utc', now())
   where id = v_order_id;

  return query
  select
    o.id,
    o.order_number,
    o.total_cents,
    o.pay_on_pickup_cents,
    o.status
  from public.orders o
  where o.id = v_order_id;
end;
$$;

-- =========================================================
-- RPC / FUNCTIONS USED BY THE APP
-- =========================================================

create or replace function public.get_employee_by_cpf(p_cpf text)
returns table (
  id uuid,
  full_name text,
  cpf text,
  role text
)
language sql
security definer
set search_path = public
as $$
  select e.id, e.full_name, e.cpf, e.role
  from public.employees e
  where public.only_digits(e.cpf) = public.only_digits(p_cpf)
    and e.active = true
  limit 1;
$$;

create or replace function public.link_employee_to_user(p_cpf text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_employee public.employees%rowtype;
begin
  v_uid := auth.uid();
  if v_uid is null then
    raise exception 'auth.uid() is null';
  end if;

  select *
    into v_employee
    from public.employees
   where public.only_digits(cpf) = public.only_digits(p_cpf)
   limit 1;

  if v_employee.id is null then
    raise exception 'Employee not found for CPF %', p_cpf;
  end if;

  update public.employees
     set user_id = v_uid,
         updated_at = timezone('utc', now())
   where id = v_employee.id;

  insert into public.profiles (user_id, full_name, role, active)
  values (
    v_uid,
    v_employee.full_name,
    case when lower(coalesce(v_employee.role, 'employee')) = 'admin' then 'admin' else 'employee' end,
    true
  )
  on conflict (user_id) do update
    set full_name = excluded.full_name,
        role = excluded.role,
        active = excluded.active,
        updated_at = timezone('utc', now());
end;
$$;

create or replace function public.get_current_profile()
returns table (
  user_id uuid,
  full_name text,
  role text,
  active boolean
)
language sql
security definer
set search_path = public
as $$
  select p.user_id, p.full_name, p.role, p.active
  from public.profiles p
  where p.user_id = auth.uid()
  limit 1;
$$;

create or replace function public.is_current_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.active = true
      and lower(coalesce(p.role, '')) = 'admin'
  )
  or exists (
    select 1
    from public.employees e
    where e.user_id = auth.uid()
      and e.active = true
      and lower(coalesce(e.role, '')) = 'admin'
  )
  or exists (
    select 1
    from public.customers c
    where c.user_id = auth.uid()
      and c.active = true
      and lower(coalesce(c.role, '')) = 'admin'
  );
$$;

create or replace function public.admin_get_employees_basic()
returns table (
  cpf text,
  full_name text
)
language sql
security definer
set search_path = public
as $$
  select e.cpf, e.full_name
  from public.employees e
  where e.active = true
  order by e.full_name asc;
$$;

create or replace function public.admin_cancel_order_v2(
  p_order_id uuid,
  p_reason text,
  p_actor_cpf text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.orders
     set status = 'cancelado',
         cancel_reason = left(coalesce(p_reason, ''), 1000),
         cancelled_at = timezone('utc', now()),
         updated_at = timezone('utc', now())
   where id = p_order_id;

  insert into public.order_admin_actions(order_id, actor_cpf, action, reason)
  values (p_order_id, p_actor_cpf, 'cancel_order', left(coalesce(p_reason, ''), 1000));
end;
$$;

create or replace function public.customer_orders_with_items(p_customer_document text)
returns table (
  id uuid,
  order_number text,
  total_items integer,
  total_value numeric,
  status text,
  created_at timestamptz,
  order_items jsonb
)
language sql
security definer
set search_path = public
as $$
  with filtered_orders as (
    select o.*
    from public.orders o
    where public.only_digits(coalesce(o.customer_document, '')) = public.only_digits(p_customer_document)
       or coalesce(o.customer_document, '') = coalesce(p_customer_document, '')
    order by o.created_at desc
  )
  select
    o.id,
    o.order_number,
    o.total_items,
    o.total_value,
    o.status,
    o.created_at,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', oi.id,
            'product_id', oi.product_id,
            'product_name', oi.product_name,
            'quantity', oi.quantity,
            'unit_price', oi.unit_price,
            'total_price', oi.total_price
          )
          order by oi.created_at asc
        )
        from public.order_items oi
        where oi.order_id = o.id
      ),
      '[]'::jsonb
    ) as order_items
  from filtered_orders o;
$$;

create or replace function public.get_top_selling_products(limit_count integer default 10)
returns table (
  product_id uuid,
  total_quantity numeric,
  total_value numeric
)
language sql
security definer
set search_path = public
as $$
  select
    oi.product_id,
    sum(coalesce(oi.quantity, 0)) as total_quantity,
    sum(coalesce(oi.quantity, 0) * coalesce(oi.unit_price_cents, 0)) / 100.0 as total_value
  from public.order_items oi
  join public.orders o on o.id = oi.order_id
  where oi.product_id is not null
    and coalesce(o.status, '') <> 'cancelado'
  group by oi.product_id
  order by total_quantity desc, total_value desc
  limit greatest(coalesce(limit_count, 10), 1);
$$;

-- =========================================================
-- DEFAULT ROWS
-- =========================================================

insert into public.carousel_settings (id, auto_mode, limit_count)
values ('00000000-0000-0000-0000-000000000001', false, 10)
on conflict (id) do nothing;

insert into public.categories (name, sort_order, active)
values
  ('Pão de Queijo', 10, true),
  ('Salgados Assados', 20, true),
  ('Salgados P/ Fritar', 30, true),
  ('Pães e Massas Doces', 40, true),
  ('Biscoito de Queijo', 50, true),
  ('Salgados Grandes', 60, true),
  ('Kits e Combos', 70, true),
  ('Alho em creme', 80, true),
  ('Outros', 90, true)
on conflict (name) do nothing;

-- =========================================================
-- STORAGE BUCKETS
-- =========================================================

insert into storage.buckets (id, name, public)
values
  ('product-images', 'product-images', true),
  ('notices', 'notices', true)
on conflict (id) do nothing;

-- =========================================================
-- RLS
-- Local/dev: permissive on purpose
-- =========================================================

alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.employees enable row level security;
alter table public.hr_users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.weight enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_admin_actions enable row level security;
alter table public.app_events enable row level security;
alter table public.notices enable row level security;
alter table public.favorites enable row level security;
alter table public.featured_products enable row level security;
alter table public.carousel_settings enable row level security;

drop policy if exists "local all profiles" on public.profiles;
create policy "local all profiles" on public.profiles for all using (true) with check (true);

drop policy if exists "local all customers" on public.customers;
create policy "local all customers" on public.customers for all using (true) with check (true);

drop policy if exists "local all employees" on public.employees;
create policy "local all employees" on public.employees for all using (true) with check (true);

drop policy if exists "local all hr_users" on public.hr_users;
create policy "local all hr_users" on public.hr_users for all using (true) with check (true);

drop policy if exists "local all categories" on public.categories;
create policy "local all categories" on public.categories for all using (true) with check (true);

drop policy if exists "local all products" on public.products;
create policy "local all products" on public.products for all using (true) with check (true);

drop policy if exists "local all weight" on public.weight;
create policy "local all weight" on public.weight for all using (true) with check (true);

drop policy if exists "local all orders" on public.orders;
create policy "local all orders" on public.orders for all using (true) with check (true);

drop policy if exists "local all order_items" on public.order_items;
create policy "local all order_items" on public.order_items for all using (true) with check (true);

drop policy if exists "local all order_admin_actions" on public.order_admin_actions;
create policy "local all order_admin_actions" on public.order_admin_actions for all using (true) with check (true);

drop policy if exists "local all app_events" on public.app_events;
create policy "local all app_events" on public.app_events for all using (true) with check (true);

drop policy if exists "local all notices" on public.notices;
create policy "local all notices" on public.notices for all using (true) with check (true);

drop policy if exists "local all favorites" on public.favorites;
create policy "local all favorites" on public.favorites for all using (true) with check (true);

drop policy if exists "local all featured_products" on public.featured_products;
create policy "local all featured_products" on public.featured_products for all using (true) with check (true);

drop policy if exists "local all carousel_settings" on public.carousel_settings;
create policy "local all carousel_settings" on public.carousel_settings for all using (true) with check (true);

drop policy if exists "local read product-images bucket" on storage.objects;
create policy "local read product-images bucket"
on storage.objects
for select
using (bucket_id = 'product-images');

drop policy if exists "local write product-images bucket" on storage.objects;
create policy "local write product-images bucket"
on storage.objects
for all
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "local read notices bucket" on storage.objects;
create policy "local read notices bucket"
on storage.objects
for select
using (bucket_id = 'notices');

drop policy if exists "local write notices bucket" on storage.objects;
create policy "local write notices bucket"
on storage.objects
for all
using (bucket_id = 'notices')
with check (bucket_id = 'notices');

commit;
